# .github/workflows/deploy.yml
name: Build and Deploy to Azure ACI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        uses: azure/docker-login@v1
        with:
          login-server: rgthinktankg3.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t rgthinktankg3.azurecr.io/myfastapiapp:latest .

      - name: Push image
        run: docker push rgthinktankg3.azurecr.io/myfastapiapp:latest

      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: rg-thinktank-g3
          name: myfastapiapp
          image: rgthinktankg3.azurecr.io/myfastapiapp:latest
          dns-name-label: myfastapiapp-${{ github.run_number }}
          location: eastus
          ports: 80
